# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-10-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180920_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurls',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
